#ifndef QUASARAAPP_GLOBAL_H
#define QUASARAAPP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUASARAPP_LIBRARY)
#  define QUASARAPPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUASARAPPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUASARAAPP_GLOBAL_H
